[package]
name = "advent_of_code_2023"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day01part1"
path = "src/day01/part1.rs"

[[bin]]
name = "day01part2"
path = "src/day01/part2.rs"

[dependencies]
